### ISSUE TITLE
GDPRNetwork.isAdNetwork() on a null object reference

### ISSUE THREAD

**Issue by rausNT** [MFlisar/GDPRDialog#52]
can not start in my application. Error
`
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.michaelflisar.gdprdialog.GDPRNetwork.isAdNetwork()' on a null object reference
        at com.michaelflisar.gdprdialog.GDPRSetup.containsAdNetwork(GDPRSetup.java:314)
        at com.michaelflisar.gdprdialog.helper.GDPRViewManager.initGeneralTexts(GDPRViewManager.java:279)
        at com.michaelflisar.gdprdialog.helper.GDPRViewManager.init(GDPRViewManager.java:154)
        at com.michaelflisar.gdprdialog.GDPRDialog.initView(GDPRDialog.java:147)
        at com.michaelflisar.gdprdialog.GDPRDialog.onCreateView(GDPRDialog.java:73)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6176)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

`

**Comment by MFlisar** [comment]
Did you add a network to the setup like following:

    new GDPRSetup(GDPRDefinitions.ADMOB)

Or did you pass `null` or nothing here?

**Comment by rausNT** [comment]
I used this code
https://github.com/MFlisar/GDPRDialog/blob/master/app/src/main/java/com/michaelflisar/gdprdialog/demo/MinimalDemoActivity.java
If you use the full code, there is no error.

**Comment by MFlisar** [comment]
If you build the example and start the minimum demo, it works... Can you try debugging this in your app?

I don't see any way to reproduce the issue...

**Comment by MFlisar** [comment]
Will close this for now as there is no activity here...
